### ISSUE TITLE
user can't add links from a word, pdf , docx or sls file that direct users to  the GCpedia page direclty

### ISSUE THREAD

**Issue by RimaSakr** [tbs-sct/gcpedia#25]
there is a work around it where he can use the hyperlink in word but this will not open the file from one click in Gcpedia, it will take him to the page where the file is downloaded and then he will have to open the file to see the info. he is asking if he can have the document open in one click

**Comment by LemieuxGen** [comment]
+1

**Comment by KevinChagnon** [comment]
+1

**Comment by Phanoix** [comment]
If I'm remembering this right, @cdegrass looked into this a while ago and found that it was more to do with a bug in MS word rather than in in our system, but I can take another look and see if anything's changed (I don't think we looked into the pdf one - is that referring to the ones generated from wiki pages in particular?).

**Comment by ToferC** [comment]
Please advise if/why this is a priority bug fix. Is a second click really critical for this user? Is this core or a fringe case? What is the user story? Thanks!

**Comment by Phanoix** [comment]
I tested this with image and .doc files and I was able to copy/paste a direct link to those files into a word (.docx) file and open both types of files directly.
I also tested the PDFs generated from GCpedia pages, and it seems to be more of a design choice of the mediawiki developers to have the direct links to files be converted into links to their pages.
